INSERT INTO rules (pattern, category, priority) VALUES 
('uber', 'Transport', 10),
('lyft', 'Transport', 10),
('united airlines', 'Travel', 10),
('delta air lines', 'Travel', 10),
('starbucks', 'Food & Drink', 10),
('mcdonalds', 'Food & Drink', 10),
('kf', 'Food & Drink', 10), -- Covers KFC
('burger king', 'Food & Drink', 10),
('whole foods', 'Groceries', 10),
('trader joes', 'Groceries', 10),
('safeway', 'Groceries', 10),
('target', 'Shopping', 5),
('amazon', 'Shopping', 5),
('netflix', 'Entertainment', 10),
('spotify', 'Entertainment', 10),
('apple.com/bill', 'Subscription', 10),
('pg&e', 'Utilities', 10),
('comcast', 'Utilities', 10),
('verizon', 'Utilities', 10),
('at&t', 'Utilities', 10),
('tectra', 'Software', 10),
('madison bicycle', 'Sports/Recreation', 10),
('gusto', 'Payroll/Income', 10);
